Matthew/review component api data
Healthy-Plate-Project/Healthy-Eating-App pull request #107
Opened 2022-09-28 17:45 UTC by MatteoThomas

Connect getRestaurant API call to ReviewsListParent component.

2022-09-28 23:42 UTC, johndavis92790 requested changes

2022-09-28 23:42 UTC, johndavis92790 commented on client/src/pages/Review/ReviewsList/ReviewsList.tsx
> +    const getRestaurantReview = getReview;
So `getReview()` needs to be awaited and to have an id passed through it for it to work properly. So for example:
```
const getRestaurantReview = await getReview("632bbba7fdc1d1d69a42f3ef");
```
But most times when you are rendering a page or component based on data coming from an asynchronous source, like an API call, you need to put the API call into a `useEffect()` hook and then store the incoming data in a `useState()` hook. Use `SingleSearchResult.tsx` as an example.

You now are probably wondering where the id that has to get passed into the `getReview()` call come from? You need to get this from the previous page or component and use the `useParams()` hook to get it from the current url. Again, the `SingleSearchResult.tsx` file is a good example of this. The `place_id` come from the parent page to this, which is the `SearchResult.tsx` file. It is passed through the `Link` tag as a `to` parameter, which basically plugs whatever string you want into the url for the next child page to read, like so:
```
 <Link to={`/single-result/${place.place_id}`}>
```
You need to also create this route on the main `App.tsx` file also so it knows how to handle this url, like so:
```
<Route
   path="/single-result/:place_id"
   element={<SingleSearchResultPage />}
/>
```

2022-09-28 23:42 UTC, johndavis92790 commented on client/src/pages/Review/ReviewsList/ReviewsListParent.tsx
> +        const data = await getRestaurant(place_id);
We can also use the `getReviewsByRestaurant()` api call here, to get our proprietary reviews, rather than just the google reviews.

2022-09-28 23:42 UTC, johndavis92790 commented on client/src/components/NavBar/NavBar.tsx
> +    console.log(saveRestaurantResults);
We should always keep these lines commented out when pushing to your branch, they are just for local testing.

2022-09-28 23:42 UTC, johndavis92790 commented on client/src/components/NavBar/NavBar.tsx
> +      </Link>
Not sure what this is for, don't we need a link here for the review stuff that you built in this PR?

2022-09-29 02:27 UTC, MatteoThomas commented on client/src/pages/Review/ReviewsList/ReviewsList.tsx
> +    const getRestaurantReview = getReview;
Ok, awesome. I'll fix it.

2022-12-15 01:12 UTC, robyng commented
@johndavis92790 to take over this PR

2023-01-05 03:43 UTC, closed without merging