Fix serverCalls.tsx
Healthy-Plate-Project/Healthy-Eating-App pull request #143
Opened 2022-11-19 05:35 UTC by johndavis92790

- Fix FavRestaurant API calls.
- Remove saveRestaurant API since it is no longer needed.

2022-11-20 19:00 UTC, robyng requested changes

2022-11-20 19:00 UTC, robyng commented on client/src/components/NavBar/NavBar.tsx
> -      </details>
keep details

2022-11-20 23:36 UTC, johndavis92790 commented on client/src/components/NavBar/NavBar.tsx
> -      </details>
Answer is in PR 140

2022-11-21 04:15 UTC, MatteoThomas approved these changes

2022-11-21 04:16 UTC, merged